name: Ejecutar generador de horarios

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  abrir-pagina:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Selenium
        run: |
          pip install selenium webdriver-manager

      - name: Abrir página y ejecutar JS
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: |
          python - <<EOF
          import os
          import time
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from selenium.webdriver.chrome.service import Service
          from webdriver_manager.chrome import ChromeDriverManager

          url = os.getenv("TARGET_URL")

          options = Options()
          options.add_argument("--headless=new")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")

          driver = webdriver.Chrome(
              service=Service(ChromeDriverManager().install()),
              options=options
          )

          print("Abriendo:", url)
          driver.get(url)

          # Esperar para que el JS genere y suba el JSON
          time.sleep(70)

          print("Página ejecutada correctamente")
          driver.quit()
          EOF
